In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("customer_churn.csv")
df.head()

,Customer_ID,Name,Gender,Age,Tenure,MonthlyCharges,SupportCalls,Churn
0,1001,Customer_1,Male,34,20,1279,1,No
1,1002,Customer_2,Female,26,113,814,0,Yes
2,1003,Customer_3,Male,50,61,536,2,No
3,1004,Customer_4,Male,70,106,647,4,Yes
4,1005,Customer_5,Male,37,35,926,1,No

In [3]:

X = df[[
    "Age",
    "Tenure",
    "MonthlyCharges",
    "SupportCalls"
]]
y = df["Churn"]
print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   Age  Tenure  MonthlyCharges  SupportCalls
0   34      20            1279             1
1   26     113             814             0
2   50      61             536             2
3   70     106             647             4
4   37      35             926             1

Target:
0     No
1    Yes
2     No
3    Yes
4     No
Name: Churn, dtype: object

In [4]:
X.describe()

               Age      Tenure  MonthlyCharges  SupportCalls
count  1000.000000  1000.00000     1000.000000   1000.000000
mean     44.294000    59.00100      897.955000      3.974000
std      15.420485    34.50202      336.538543      2.622251
min      18.000000     1.00000      300.000000      0.000000
25%      31.000000    29.00000      606.750000      2.000000
50%      44.000000    59.00000      881.000000      4.000000
75%      57.000000    89.00000     1198.000000      6.000000
max      70.000000   120.00000     1499.000000      8.000000