In [1]:
import pandas as pd

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

data = {
    "Study_Hours": [6, 2, 5, 1, 7, 3, 8, 2, 6, 4],
    "Attendance": [90, 60, 85, 50, 95, 65, 92, 55, 88, 75],
    "Marks": [75, 30, 65, 25, 80, 40, 85, 35, 70, 55],
    "Result": [
        "Pass", "Fail", "Pass", "Fail", "Pass",
        "Fail", "Pass", "Fail", "Pass", "Pass"
    ]
}

In [15]:
df=pd.DataFrame(data)
df

   Study_Hours  Attendance  Marks Result
0            6          90     75   Pass
1            2          60     30   Fail
2            5          85     65   Pass
3            1          50     25   Fail
4            7          95     80   Pass
5            3          65     40   Fail
6            8          92     85   Pass
7            2          55     35   Fail
8            6          88     70   Pass
9            4          75     55   Pass

In [16]:
x=df[["Study_Hours","Attendance"]]
y=df["Result"]

y=y.map({
    "Fail":0,
    "Pass":1
})

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42
)

Scaler = StandardScaler()

x_train = Scaler.fit_transform(x_train)

x_test = Scaler.transform(x_test)

In [18]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
print("Predicted labels:", y_pred)

Predicted labels: [1 0 0]

In [19]:
print(x_test)

[[ 0.54173634  0.62577183]
 [-1.1436656  -1.03167789]
 [-0.72231512 -0.73570472]]

In [20]:
print(x_train)

[[ 0.54173634  0.7441611 ]
 [-1.1436656  -1.32765105]
 [ 0.12038585  0.44818794]
 [-0.30096463 -0.14375839]
 [ 0.96308682  1.04013427]
 [-1.56501609 -1.62362422]
 [ 1.38443731  0.86255037]]

In [21]:
print(y_test)

8    1
1    0
5    0
Name: Result, dtype: int64

In [22]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [23]:
data = {
    "Age": [25, 35, 45, 50, 60, 30, 40, 55, 65, 28,
            48, 52, 33, 70, 58, 42, 37, 62, 29, 67],

    "BP": [118, 125, 140, 145, 165, 120, 135, 155, 170, 115,
           142, 150, 122, 175, 160, 130, 128, 168, 119, 172],

    "Heart_Rate": [70, 75, 85, 88, 96, 72, 80, 92, 100, 68,
                   86, 90, 74, 105, 95, 78, 76, 98, 71, 102],

    "Sugar_Level": [90, 100, 130, 145, 180, 95, 115, 160, 200, 88,
                    135, 150, 105, 210, 175, 110, 102, 190, 92, 205],

    "Exercise_Hours": [6, 5, 2, 2, 1, 7, 4, 1, 0, 7,
                       2, 1, 6, 0, 1, 4, 5, 1, 6, 0],

    "BMI": [22, 24, 28, 29, 32, 21, 26, 31, 34, 22,
            29, 30, 23, 35, 32, 25, 24, 33, 21, 34],

    "Smoking": [0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
                1, 1, 0, 1, 1, 0, 0, 1, 0, 1],

    "Risk_Status": [
        "Low", "Low", "Medium", "Medium", "High",
        "Low", "Low", "High", "High", "Low",
        "Medium", "High", "Low", "High", "High",
        "Low", "Low", "High", "Low", "High"
    ]
}

df = pd.DataFrame(data)

df.head()

   Age   BP  Heart_Rate  Sugar_Level  Exercise_Hours  BMI  Smoking Risk_Status
0   25  118          70           90               6   22        0         Low
1   35  125          75          100               5   24        0         Low
2   45  140          85          130               2   28        1      Medium
3   50  145          88          145               2   29        1      Medium
4   60  165          96          180               1   32        1        High

In [24]:
print(df.shape)
print(df.info())

(20, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             20 non-null     int64
 1   BP              20 non-null     int64
 2   Heart_Rate      20 non-null     int64
 3   Sugar_Level     20 non-null     int64
 4   Exercise_Hours  20 non-null     int64
 5   BMI             20 non-null     int64
 6   Smoking         20 non-null     int64
 7   Risk_Status     20 non-null     object
dtypes: int64(7), object(1)
memory usage: 1.4+ KB
None

In [25]:
X = df[
    [
        "Age",
        "BP",
        "Heart_Rate",
        "Sugar_Level",
        "Exercise_Hours",
        "BMI",
        "Smoking"
    ]
]

y = df["Risk_Status"]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [27]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [28]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [29]:
y_pred = knn.predict(X_test)

print(y_pred)

['High' 'High' 'Low' 'High' 'Low']

In [30]:
new_patient = [[
    55,
    155,
    92,
    170,
    1,
    31,
    1
]]

new_patient_scaled = scaler.transform(new_patient)

prediction = knn.predict(new_patient_scaled)

print("Predicted Risk Status:", prediction[0])

Predicted Risk Status: High

c:\Users\thema\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [1]:
import pandas as pd

In [11]:
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import( accuracy_score,precision_score,recall_score,f1_score,confusion_matrix)

data={
    "age":[22,24,25,23,27,21,25,29,21,29,30,31],
    "salary":[25000,30000,32000,27000,50000,20000,32000,55000,50000,25000,20000,20000],
    "purchase":[0,1,1,0,1,0,1,1,1,0,0,1]
    
}

df=pd.DataFrame(data)
df

    age  salary  purchase
0    22   25000         0
1    24   30000         1
2    25   32000         1
3    23   27000         0
4    27   50000         1
5    21   20000         0
6    25   32000         1
7    29   55000         1
8    21   50000         1
9    29   25000         0
10   30   20000         0
11   31   20000         1

In [12]:
x=df[["age","salary"]]
y=df["purchase"]

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [14]:
model=DecisionTreeClassifier(max_depth=3)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

In [15]:
print("accuracy:",accuracy_score(y_test,y_pred))

accuracy: 0.3333333333333333

In [16]:
print("precision:",precision_score(y_test,y_pred))

precision: 0.0

In [17]:
print("Recall:",recall_score(y_test,y_pred))

Recall: 0.0

c:\Users\thema\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [18]:
print("F1:",f1_score(y_test,y_pred))

F1: 0.0

In [19]:
print("confusion_matrix:",confusion_matrix(y_test,y_pred))

confusion_matrix: [[1 2]
 [0 0]]