In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import(accuracy_score,classification_report,confusion_matrix)

In [4]:
data = {
    "Study_Hours": [2, 5, 1, 6, 8, 3, 7, 2, 9, 4,
                    1, 6, 8, 3, 7, 2, 10, 4, 5, 9],

    "Attendance": [60, 85, 50, 90, 95, 70, 92, 55, 98, 80,
                   45, 88, 94, 65, 90, 58, 99, 75, 82, 96],

    "Assignment_Marks": [40, 75, 30, 85, 90, 55, 88, 35, 95, 70,
                         25, 82, 92, 50, 85, 38, 98, 65, 72, 94],

    "Previous_Marks": [35, 70, 25, 80, 85, 50, 82, 30, 90, 65,
                       20, 78, 88, 45, 80, 32, 95, 60, 68, 91],

    "Internal_Marks": [38, 72, 28, 82, 88, 52, 85, 32, 92, 68,
                       22, 80, 90, 48, 82, 35, 96, 62, 70, 93],

    "Result": [
        "Fail", "Pass", "Fail", "Pass", "Pass",
        "Fail", "Pass", "Fail", "Pass", "Pass",
        "Fail", "Pass", "Pass", "Fail", "Pass",
        "Fail", "Pass", "Pass", "Pass", "Pass"
    ]
}

df = pd.DataFrame(data)

df

,Study_Hours,Attendance,Assignment_Marks,Previous_Marks,Internal_Marks,Result
0,2,60,40,35,38,Fail
1,5,85,75,70,72,Pass
2,1,50,30,25,28,Fail
3,6,90,85,80,82,Pass
4,8,95,90,85,88,Pass
5,3,70,55,50,52,Fail
6,7,92,88,82,85,Pass
7,2,55,35,30,32,Fail
8,9,98,95,90,92,Pass
9,4,80,70,65,68,Pass
10,1,45,25,20,22,Fail
11,6,88,82,78,80,Pass
12,8,94,92,88,90,Pass
13,3,65,50,45,48,Fail
14,7,90,85,80,82,Pass
15,2,58,38,32,35,Fail
16,10,99,98,95,96,Pass
17,4,75,65,60,62,Pass
18,5,82,72,68,70,Pass
19,9,96,94,91,93,Pass

In [5]:
x = df[
    [
    "Study_Hours",
    "Attendance",
    "Assignment_Marks",
    "Previous_Marks",
    "Internal_Marks"
]
]

y=df["Result"]

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42,stratify=y)

In [7]:
model=RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [8]:
y_pred=model.predict(x_test)
print(y_pred)

['Fail' 'Fail' 'Pass' 'Pass' 'Pass']

In [9]:
print("accuracy:",accuracy_score(y_test,y_pred))

accuracy: 1.0

In [10]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         2
        Pass       1.00      1.00      1.00         3

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

In [11]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[2 0]
 [0 3]]

In [13]:
importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

            Feature  Importance
3    Previous_Marks        0.23
0       Study_Hours        0.22
4    Internal_Marks        0.21
1        Attendance        0.19
2  Assignment_Marks        0.15

In [14]:
new_student = [[
    6,    
    90,   
    85,   
    80,
    82    
]]

prediction = model.predict(new_student)

print("Prediction:", prediction[0])

Prediction: Pass

c:\Users\thema\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [15]:
import pandas as pd

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import(accuracy_score,classification_report,confusion_matrix)

In [18]:
data = {
    "Tenure": [2, 10, 24, 36, 5, 48, 12, 60, 3, 30,
               8, 40, 15, 55, 4, 20, 35, 50, 6, 45],

    "Monthly_Charges": [80, 60, 50, 45, 90, 40, 70, 35, 95, 55,
                        85, 42, 65, 38, 100, 58, 48, 40, 88, 44],

    "Support_Calls": [5, 2, 1, 0, 6, 0, 3, 0, 7, 1,
                      5, 0, 2, 0, 8, 2, 1, 0, 6, 1],

    "Total_Charges": [160, 600, 1200, 1620, 450, 1920, 840, 2100, 285,
                      1650, 680, 1680, 975, 2090, 400, 1160, 1680,
                      2000, 528, 1980],

    "Contract_Length": [1, 12, 24, 24, 1, 36, 12, 36, 1, 24,
                        1, 36, 12, 36, 1, 12, 24, 36, 1, 24],

    "Churn": [
        "Yes", "No", "No", "No", "Yes",
        "No", "Yes", "No", "Yes", "No",
        "Yes", "No", "Yes", "No", "Yes",
        "No", "No", "No", "Yes", "No"
    ]
}

df = pd.DataFrame(data)

df

,Tenure,Monthly_Charges,Support_Calls,Total_Charges,Contract_Length,Churn
0,2,80,5,160,1,Yes
1,10,60,2,600,12,No
2,24,50,1,1200,24,No
3,36,45,0,1620,24,No
4,5,90,6,450,1,Yes
5,48,40,0,1920,36,No
6,12,70,3,840,12,Yes
7,60,35,0,2100,36,No
8,3,95,7,285,1,Yes
9,30,55,1,1650,24,No
10,8,85,5,680,1,Yes
11,40,42,0,1680,36,No
12,15,65,2,975,12,Yes
13,55,38,0,2090,36,No
14,4,100,8,400,1,Yes
15,20,58,2,1160,12,No
16,35,48,1,1680,24,No
17,50,40,0,2000,36,No
18,6,88,6,528,1,Yes
19,45,44,1,1980,24,No

In [19]:
X = df[
    [
        "Tenure",
        "Monthly_Charges",
        "Support_Calls",
        "Total_Charges",
        "Contract_Length"
    ]
]

y = df["Churn"]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [21]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [22]:
y_pred = model.predict(X_test)

print(y_pred)

['No' 'No' 'Yes' 'Yes' 'No']

In [23]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       1.00      1.00      1.00         3
         Yes       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

In [25]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[3 0]
 [0 2]]

In [26]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

           Feature  Importance
1  Monthly_Charges    0.337817
0           Tenure    0.241654
3    Total_Charges    0.166069
4  Contract_Length    0.150256
2    Support_Calls    0.104204

In [ ]:
new_customer = [[
    4,      
    90,     
    6,      
    360,    
    1      
]]

prediction = model.predict(new_customer)

print("Churn Prediction:", prediction[0])

Churn Prediction: Yes

c:\Users\thema\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(